### ISSUE TITLE
tt-rss_reeder_theme doesn't work with git version tt-rss

### ISSUE THREAD

**Issue by atomlab** [tschinz/tt-rss_reeder_theme#13]
Hi. I installed new version tt-rss from git and tt-rss_reeder_theme isn't work now. 
I can't see "reeder.css" in Preferences->Theme->Select one of the available CSS themes.

**Comment by Phil57** [comment]
Change the first line of the .css to

+/* supports-version:15.7 */

**Comment by atomlab** [comment]
Thanks!

**Comment by Phil57** [comment]
I made a pull request to @tschinz 2 weeks ago to fix this issue, but he doesn't seem to be around.

**Comment by tschinz** [comment]
didn't saw it, slipped throught the information flood. Will do it these next days.

thanks @Phil57

**Comment by pipisauto** [comment]
thanks, I am using tt-rss V18.12, I edited the CSS and Changed the first line to my current version

**Comment by tschinz** [comment]
Hi @pipisauto,
Create a Pull Request and I'll merge it.
I don't actively develop the theme anymore, if somebody wants to take it over please contact me.
