### ISSUE TITLE
Latest GIT broke cdm icons

### ISSUE THREAD

**Issue by mcbyte-it** [tschinz/tt-rss_reeder_theme#14]
last week Tiny Tiny RSS made a commit to render the cdm footer icons as table, and removed the "float: right" style from the div tag, here is the commit log: https://tt-rss.org/gitlab/fox/tt-rss/commit/bc20cb9fad53bc8575a6463d24d9f44f2883c482#30b78a742d7894232cc7f3cbd1d8a0f15b0b9cd3_743_740

With this commit, the cdm icons in the Reeder theme are all aligned to the left:
![ttrss](https://cloud.githubusercontent.com/assets/3248742/9323763/a8d9add0-458c-11e5-94e8-d3a0a4a8bf51.png)

My quick fix was a new css statement in reeder.css:
```
div.cdmFooter > div {
  float: right;
}
```

**Comment by tschinz** [comment]
Thanks, done
