### ISSUE TITLE
Store fonts locally instead of requesting from fonts.googleapis.com

### ISSUE THREAD

**Issue by NerdmindDE** [tschinz/tt-rss_reeder_theme#20]
Fonts should be stored locally for privacy reasons (and for those who not allowing  `fonts.gstatic.com` and `fonts.googleapis.com` within the `Content-Security-Policy`-Header). Thanks! =)

**Comment by tschinz** [comment]
I'll look into it. But I'm slammed with work at the moment. But good idea thanks for the input.

**Comment by tschinz** [comment]
Done, OpenSans Font is now locally stored see commit 78e1f8209356216c1e184f0fa0cf03bac3461faf
