### ISSUE TITLE
css menu with scrollbar

### ISSUE THREAD

**Issue by wicope** [tschinz/tt-rss_reeder_theme#21]
![2016-12-27-114042_2560x1024_scrot](https://cloud.githubusercontent.com/assets/13379613/21502531/c66b924a-cc50-11e6-872a-4eb36ffb699f.png)

http://stackoverflow.com/questions/21983819/making-a-drop-down-menu-scrollable

<div id="dijit_PopupMenuItem_0_dropdown"
class="dijitPopup dijitMenuPopup" 
...>

dijitPopup (found)
dijitMenuPopup (not found)

Posible solution:
    max-height: 500px;
    overflow-y: scroll;

.dijitPopup {
    background-color: transparent;
    border: 0 none;
    margin: 0;
    padding: 0;
    position: absolute;
    max-height: 500px;
    overflow-y: scroll;
}

http://xxx/lib/dijit/themes/claro/claro.css

**Comment by tschinz** [comment]
check if it's ok now with the commit: c7c243fce08b8791809b33b51300cb80f271202c
