### ISSUE TITLE
Not able to use the theme anymore with Tiny Tiny RSS v17.1 (e934d63)

### ISSUE THREAD

**Issue by kobemtl** [tschinz/tt-rss_reeder_theme#22]
Hi, I love this theme and been using it since I found it. I'd like to appreciate the work you done. Now with latest tt-rss update, Tiny Tiny RSS v17.1 (e934d63), I couldn't use it anymore. Could you please take a look? 

Thanks again.

**Comment by tschinz** [comment]
see commit f601ac032e0db91825dd4831e37f4448bd324b9b. Everytime the tt-rss changes it's version 
fox decided that it's a good idea that every theme needs to modify one line to continuing working. Next time just change that line and make a pull request so I don't have to ;-)

Cheers

**Comment by wicope** [comment]
sed -i 's/17.1/17.4/' /var/www/themes/reeder.css

**Comment by tschinz** [comment]
see commit bfffe680acc3b34befcd3deef519b9c52f7ce1da. thanks @wicope
