### ISSUE TITLE
Unread badges hidden on long categories titles

### ISSUE THREAD

**Issue by UksusoFF** [tschinz/tt-rss_reeder_theme#23]
![image](https://cloud.githubusercontent.com/assets/1931442/24060536/166fdc46-0b6d-11e7-803e-5143a47daea0.png)

Tiny Tiny RSS v17.1 (63f0ed3)

**Comment by tschinz** [comment]
@UksusoFF thanks for the improvement. I've never had such long names so I didn't see this error. #24
