### ISSUE TITLE
What License is this under?

### ISSUE THREAD

**Issue by dasJ** [tschinz/tt-rss_reeder_theme#29]
I'd like to package this theme for NixOS, but it lacks a LICENSE file so I don't know what license to package it under.
Could you add a proper LICENSE file?

**Comment by tschinz** [comment]
Hello why would you need this for NixOS? The license would be [http://www.wtfpl.net/about/](http://www.wtfpl.net/about/) 
;-) 
Hope this helps

**Comment by dasJ** [comment]
Thank you!

**Comment by dasJ** [comment]
But I'm not sure if I can package this, because it's currently broken
